### ISSUE TITLE
[Help] Install Issues-Windows

### ISSUE THREAD

**Issue by y0himba** [DrewThomasson/ebook2audiobook#169] opened 2024-12-31 18:58 UTC
Hello.  My wife is recently blind, and when I saw this, I literally whooped out loud.  I can convert her books to audio!  For free or a small donation!

However, I am not very tech savvy, and I am having issues with the install.  Got clone fails first, I restore it, then I manually extract the invalid paths (see below) and that gets it cloned and checked out. 

Next, I run `ebook2audiobook.cmd` and get a host of errors. I don't understand any of them.  The "Docker" thing is way out of my league. I just want to convert her books to audio for her, easily.  It also fails to import `unidic` saying no module is found. 

I have tried to run `conda init cmd.exe`. I have tried installing `pydantic-core`, `pyee` manually, tried running the suggested `pip install --force-reinstall --no-deps pydantic-core==2.23.4` but I cannot even activate the vEnv. 

please see the screenshots below.  Thank you for any help as this is an absolute BOON to my wife and I. 

If there is any information I can collect and post to this end, please just let me know?  Go easy on me also, I am an old vet and just trying to get some help here.  

![y0himba-Administrator_CWindowssys-343](https://github.com/user-attachments/assets/cee1ed22-dbe2-4500-8a47-05a827dbe160)

![y0himba-Administrator_CWindowssys-344](https://github.com/user-attachments/assets/48bc5261-ca61-47f6-819c-342bba0fa880)

![y0himba-Administrator_CWindowssys-345](https://github.com/user-attachments/assets/9cf315b4-bc6b-4597-bc4b-4c78d5fe6a45)

![y0himba-Administrator_CWindowssys-346](https://github.com/user-attachments/assets/36588a01-7b33-4bc7-ae4a-16b1a0d9f250)

**Comment by titusthef0x** [comment] 2024-12-31 21:40
Had the same problem with cloning on windows try the following inside the folder:

`git config core.protectNTFS false`

and then what you did:

`git restore --source=HEAD :/`

There should now be files inside the ebook2audiobook folder and you can go on

**Comment by DrewThomasson** [comment] 2024-12-31 22:43
It's a bug That's being fixed in the next PR :)

This is a duplicate of https://github.com/DrewThomasson/ebook2audiobook/issues/126

**Closed** 2024-12-31 22:44 UTC
Labels: duplicate, windows

**Comment by thre3eye** [comment] 2025-01-02 21:06
FYI - just stumbled across this today. @titusthef0x workaround worked around it, but a regular checkout on win still seems to fail.

`PS C:\Data\Tools> git clone https://github.com/DrewThomasson/ebook2audiobook.git
Cloning into 'ebook2audiobook'...
remote: Enumerating objects: 2727, done.
remote: Counting objects: 100% (672/672), done.
remote: Compressing objects: 100% (307/307), done.
remote: Total 2727 (delta 507), reused 365 (delta 365), pack-reused 2055 (from 4)
Receiving objects: 100% (2727/2727), 202.98 MiB | 10.28 MiB/s, done.
Resolving deltas: 100% (1405/1405), done.
error: invalid path 'voices/con/adult/female/.gitkeep'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

**Comment by y0himba** [comment] 2025-01-02 22:36
That is the error in my screenshots. It's being worked on, known bug according to above.

Can anyone tell me what to do about the Conda errors in my original post?  Please and thank you?

**Comment by ROBERT-MCDOWELL** [comment] 2025-01-02 22:41
just try 
conda init

**Comment by y0himba** [comment] 2025-01-02 22:43
> just try conda init

I have tried to run conda init cmd.exe. I have tried installing pydantic-core, pyee manually, tried running the suggested pip install --force-reinstall --no-deps pydantic-core==2.23.4 but I cannot even activate the vEnv.

**Comment by titusthef0x** [comment] 2025-01-02 22:49
> > just try conda init
> 
> I have tried to run conda init cmd.exe. I have tried installing pydantic-core, pyee manually, tried running the suggested pip install --force-reinstall --no-deps pydantic-core==2.23.4 but I cannot even activate the vEnv.

I used PowerShell 7 (x64) as administrator instead of cmd.exe and never ran into those problems. Maybe try that.

**Comment by y0himba** [comment] 2025-01-02 22:53
> > > just try conda init
> > 
> > 
> > I have tried to run conda init cmd.exe. I have tried installing pydantic-core, pyee manually, tried running the suggested pip install --force-reinstall --no-deps pydantic-core==2.23.4 but I cannot even activate the vEnv.
> 
> I used PowerShell 7 (x64) as administrator instead of cmd.exe and never ran into those problems. Maybe try that.

`PS C:\Tools\ebook2audiobook> conda init
WARNING: Cannot install xonsh wrapper without a python interpreter in prefix: C:\Users\y0himba\AppData\Local\Temp\_MEI605082
ERROR during elevated execution.
  rc: [WinError 0] The operation completed successfully.
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\Scripts\conda.exe
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\Scripts\conda-env.exe
modified      C:\Users\y0himba\AppData\Local\Temp\_MEI605082\Scripts\conda-script.py
modified      C:\Users\y0himba\AppData\Local\Temp\_MEI605082\Scripts\conda-env-script.py
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\condabin\conda.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\Library\bin\conda.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\condabin\_conda_activate.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\condabin\rename_tmp.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\condabin\conda_auto_activate.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\condabin\conda_hook.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\Scripts\activate.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\condabin\activate.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\condabin\deactivate.bat
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\Scripts\activate
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\Scripts\deactivate
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\etc\profile.d\conda.sh
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\etc\fish\conf.d\conda.fish
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\shell\condabin\Conda.psm1
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\shell\condabin\conda-hook.ps1
needs sudo    C:\Users\y0himba\AppData\Local\Temp\_MEI605082\etc\profile.d\conda.csh
modified      F:\Documents\PowerShell\profile.ps1
modified      F:\Documents\WindowsPowerShell\profile.ps1
modified      HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun

==> For changes to take effect, close and re-open your current shell. <==

Operation failed.
PS C:\Tools\ebook2audiobook>`

**Comment by ROBERT-MCDOWELL** [comment] 2025-01-02 23:00
you have an issue with your user permissions. apparently it needs administrator privileges...   which is a non common state
